version: '3'
services:
  jenkins:
    container_name: srvjenkins
    image: jenkinsci/jenkins
    build:
      context: srvjenkins    
    ports:
      - "8282:8080"
    volumes:
      - /home/docker/srvjenkins:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: srvapp
    image: imgsrvapp
    build:
      context: srvapp
    networks:
      - net
  db_host:
    container_name: srvdb
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=test"
    volumes:
      - "/home/docker/srvdb:/var/lib/mysql"
    networks:
      - net
  web:
    container_name: srvweb
    image: imgweb
    build:
      context: srvweb
    ports:
      - "80:80"
    networks:
      - net
  git:
    container_name: srvgitlab
    hostname: gitlab.example.com
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - "/home/docker/srvgitlab/config:/etc/gitlab"
      - "/home/docker/srvgitlab/logs:/var/log/gitlab"
      - "/home/docker/srvgitlab/data:/var/opt/gitlab"
    image: gitlab/gitlab-ce
    networks:
      - net
networks:
  net:
