version: '3'
services:
  jenkins:
    container_name: devjenkins
    image: jenkinsci/jenkins
    build:
      context: ansible     
    ports:
      - "8080:8080"
    volumes:
      - /home/docker/jenkins:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: devapp
    image: imgapp
    build:
      context: app
    networks:
      - net
  db_host:
    container_name: dbaws
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - /home/docker/mysql:/var/lib/mysql
    networks:
      - net
  git:
    container_name: srvgit
    hostname: gitlab.example.com
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/home/docker/gitlab/config:/etc/gitlab"
      - "/home/docker/gitlab/logs:/var/log/gitlab"
      - "/home/docker/gitlab/data:/var/opt/gitlab"
    image: gitlab/gitlab-ce
    networks:
      - net
networks:
  net:
